//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_API.Edm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Pk_Login_Id { get; set; }
        public string Username { get; set; }
        public byte[] PasswordHash { get; set; }
        public Nullable<System.Guid> PasswordSalt { get; set; }
        public Nullable<int> Fk_Person_Id { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
